spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://seminar-db.cwcfnggnsjrh.ap-northeast-2.rds.amazonaws.com:3306/myseminarDB
    username: spring
    password: springseminar
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: create-drop

auth.jwt:
  issuer: WAFFLE_STUDIO
  jwtSecret: WAFFLE_STUDIO_SPRING_AND_KOTLIN_SEMINAR_SECRET_KEY
  jwtExpiration: 3600